[workspace]
members = ["crates/client-lib", "crates/common", "crates/fibonacci/client", "crates/fibonacci/program", "crates/node"]
resolver = "2"

[workspace.dependencies]
alloy = "1.0.30"
bincode = "1.3.3"
clap = { version = "4.5.47", features = ["derive"] }
client-lib = { path = "crates/client-lib" }
common = { path = "crates/common" }
crossterm = "0.29.0"
dotenv = "0.15.0"
libp2p = { version = "0.56.0", features = ["gossipsub", "macros", "mdns", "noise", "tcp", "tokio", "yamux"] }
log = "0.4.28"
serde = "1.0.221"
sp1-sdk = "5.2.1"
sp1-zkvm = "5.2.1"
tokio = "1.47.1"
tokio-stream = "0.1.17"
tracing = "0.1.41"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.20"
tui-logger = "0.17.3"
ratatui = "0.29.0"
